// qa/live.mjs — TEAM-4181 Phase 2 live browser verification (Playwright/Chromium)
// Runs every scenario twice: viewport 1280x900 and 320x900.
// Real time only — no fake timers. Appends one log line per assertion to
// qa/TEAM-4181-live-log.md as | viewport | scenario | check | expected | actual | PASS/FAIL |
//
// Does not touch anything under src/. Writes only to docs/ and qa/.

import { chromium } from 'playwright'
import { appendFileSync, writeFileSync, mkdirSync } from 'node:fs'

const URL = 'http://127.0.0.1:5173/'
const LOG = 'qa/TEAM-4181-live-log.md'
const DOCS = 'docs'
const UNDO_WINDOW_MS = 5000

mkdirSync(DOCS, { recursive: true })
mkdirSync('qa', { recursive: true })

// ---------------------------------------------------------------- log plumbing

const results = [] // { viewport, scenario, check, expected, actual, pass }
const consoleMessages = [] // { viewport, scenario, kind, text }
let ctx = { viewport: '-', scenario: '-' }

writeFileSync(
  LOG,
  `# TEAM-4181 — Phase 2 live browser verification log\n\n` +
    `Generated by \`qa/live.mjs\` against ${URL} (vite dev server), Playwright Chromium.\n` +
    `Real waits only — no fake timers. Undo window under test: ${UNDO_WINDOW_MS} ms.\n\n` +
    `| viewport | scenario | check | expected | actual | PASS/FAIL |\n` +
    `| --- | --- | --- | --- | --- | --- |\n`,
)

function cell(v) {
  if (v === undefined) return '_undefined_'
  if (v === null) return '_null_'
  let s = typeof v === 'string' ? v : JSON.stringify(v)
  s = s.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ⏎ ')
  if (s.length > 300) s = s.slice(0, 297) + '...'
  if (s === '') return '_(empty string)_'
  return '`' + s + '`'
}

// Records a check. `pass` may be a boolean, or omitted for INFO-only rows.
function check(name, expected, actual, pass) {
  const verdict = pass === undefined ? 'INFO' : pass ? 'PASS' : 'FAIL'
  results.push({ ...ctx, check: name, expected, actual, verdict })
  appendFileSync(
    LOG,
    `| ${ctx.viewport} | ${ctx.scenario} | ${name} | ${cell(expected)} | ${cell(actual)} | ${verdict} |\n`,
  )
}

function eq(name, expected, actual) {
  const pass = JSON.stringify(expected) === JSON.stringify(actual)
  check(name, expected, actual, pass)
  return pass
}

function info(name, actual) {
  check(name, '(observation)', actual, undefined)
}

// ------------------------------------------------------------------- page prep

async function newPage(context) {
  const page = await context.newPage()
  page.on('console', (m) => {
    consoleMessages.push({ ...ctx, kind: `console.${m.type()}`, text: m.text() })
  })
  page.on('pageerror', (e) => {
    consoleMessages.push({ ...ctx, kind: 'pageerror', text: String(e && e.message ? e.message : e) })
  })
  await page.goto(URL, { waitUntil: 'load' })
  await page.waitForSelector('section.activity-feed')
  return page
}

const SEED_COUNT = 25

async function seed(page) {
  await page.evaluate(() => {
    localStorage.clear()
  })
  await page.evaluate(() => {
    const now = Date.now()
    const items = Array.from({ length: 25 }, (_, i) => ({
      id: 'qa-' + i,
      type: 'settings',
      description: 'QA seeded entry ' + i,
      timestamp: now - i * 60000,
    }))
    localStorage.setItem('demo.activity', JSON.stringify(items))
  })
  await page.reload({ waitUntil: 'load' })
  await page.waitForSelector('section.activity-feed')
}

async function clearStorage(page) {
  await page.evaluate(() => localStorage.clear())
  await page.reload({ waitUntil: 'load' })
  await page.waitForSelector('section.activity-feed')
}

// ------------------------------------------------------------- DOM read helper

// One round-trip snapshot of everything the assertions need.
async function snap(page) {
  return page.evaluate(() => {
    const section = document.querySelector('section.activity-feed')
    const status = section ? section.querySelector('[role=status]') : null
    const heading = document.querySelector('#activity-feed-title')
    const notice = section ? section.querySelector('.activity-feed__notice') : null
    const btns = section ? Array.from(section.querySelectorAll('button')) : []
    const byName = (n) => btns.find((b) => (b.textContent || '').trim() === n) || null
    const clearBtn = byName('Clear activity')
    const undoBtn = byName('Undo')
    const empty = section ? section.querySelector('.activity-feed__empty') : null
    const ae = document.activeElement
    const box = (el) => {
      if (!el) return null
      const r = el.getBoundingClientRect()
      return { x: r.x, y: r.y, w: r.width, h: r.height }
    }
    return {
      liCount: section ? section.querySelectorAll('li').length : -1,
      ulCount: section ? section.querySelectorAll('ul').length : -1,
      roleListCount: section ? section.querySelectorAll('[role=list]').length : -1,
      descriptions: section
        ? Array.from(section.querySelectorAll('.activity-feed__description')).map((p) =>
            (p.textContent || '').trim(),
          )
        : [],
      statusPresent: !!status,
      statusCount: section ? section.querySelectorAll('[role=status]').length : -1,
      statusTag: status ? status.tagName : null,
      statusText: status ? (status.textContent || '').trim() : null,
      statusDisplay: status ? getComputedStyle(status).display : null,
      clearPresent: !!clearBtn,
      undoPresent: !!undoBtn,
      emptyPresent: !!empty,
      emptyText: empty ? (empty.textContent || '').trim() : null,
      noticePosition: notice ? getComputedStyle(notice).position : null,
      sectionBox: box(section),
      undoBox: box(undoBtn),
      clearBox: box(clearBtn),
      activeTag: ae ? ae.tagName : null,
      activeId: ae ? ae.id || null : null,
      activeText: ae ? (ae.textContent || '').trim().slice(0, 40) : null,
      activeIsUndo: !!undoBtn && ae === undoBtn,
      activeIsClear: !!clearBtn && ae === clearBtn,
      activeIsHeading: !!heading && ae === heading,
      scrollWidth: document.documentElement.scrollWidth,
      raw: localStorage.getItem('demo.activity'),
    }
  })
}

function storedIds(raw) {
  try {
    const v = JSON.parse(raw)
    return Array.isArray(v) ? v.map((e) => e.id) : null
  } catch {
    return null
  }
}

function storedLen(raw) {
  const ids = storedIds(raw)
  return ids === null ? null : ids.length
}

function boxInside(inner, outer) {
  if (!inner || !outer) return false
  return (
    inner.x >= outer.x - 0.5 &&
    inner.y >= outer.y - 0.5 &&
    inner.x + inner.w <= outer.x + outer.w + 0.5 &&
    inner.y + inner.h <= outer.y + outer.h + 0.5
  )
}

const clearBtnOf = (page) => page.getByRole('button', { name: 'Clear activity' })
const undoBtnOf = (page) => page.getByRole('button', { name: 'Undo', exact: true })
const toggleOf = (page) => page.getByRole('button', { name: 'Toggle email notifications' })

const wait = (ms) => new Promise((r) => setTimeout(r, ms))
const EXPECTED_EMPTY_COPY = 'No recent activity yet. Actions you take will show up here.'

// ==================================================================== scenarios

// S1 + S2 share one page: S2 must run inside the live 5s window opened by S1.
async function s1s2(page, vp, narrow) {
  ctx = { viewport: vp, scenario: 'S1 Clear' }
  await seed(page)

  let s = await snap(page)
  eq('visible li count after seeding 25', 20, s.liCount)
  eq('Clear activity button present with entries', true, s.clearPresent)
  const before = s.descriptions.slice()
  info('ordered li descriptions before clear (first 3)', before.slice(0, 3))
  eq('stored entry count before clear', SEED_COUNT, storedLen(s.raw))

  const tClear = Date.now()
  await clearBtnOf(page).click()
  s = await snap(page)

  eq('li count after Clear', 0, s.liCount)
  eq('ul count in section after Clear', 0, s.ulCount)
  eq('status text after Clear', 'Activity cleared.', s.statusText)
  eq('Undo button visible after Clear', true, s.undoPresent)
  eq('Undo bounding box lies inside section.activity-feed', true, boxInside(s.undoBox, s.sectionBox))
  check(
    '.activity-feed__notice computed position is not fixed/absolute',
    'not fixed/absolute',
    s.noticePosition,
    s.noticePosition !== 'fixed' && s.noticePosition !== 'absolute',
  )
  eq("localStorage 'demo.activity' immediately after Clear", '[]', s.raw)
  eq('Clear activity button NOT present after Clear', false, s.clearPresent)
  eq('empty-state paragraph NOT present during undo window', false, s.emptyPresent)

  await page.mouse.move(0, 0) // park the pointer so buttons render in rest style
  await page.screenshot({
    path: narrow ? `${DOCS}/TEAM-4162-narrow-clear.png` : `${DOCS}/TEAM-4162-clear.png`,
  })

  // ---- S2, still inside the window opened above
  ctx = { viewport: vp, scenario: 'S2 Undo' }
  const elapsed = Date.now() - tClear
  check(
    'Undo clicked while still inside the undo window',
    `< ${UNDO_WINDOW_MS} ms since Clear`,
    `${elapsed} ms`,
    elapsed < UNDO_WINDOW_MS,
  )
  await undoBtnOf(page).click()
  s = await snap(page)

  eq('20 li descriptions restored in identical order', before, s.descriptions)
  eq('stored entry count after Undo', SEED_COUNT, storedLen(s.raw))
  eq(
    'stored ids after Undo match seed order qa-0..qa-24',
    Array.from({ length: SEED_COUNT }, (_, i) => 'qa-' + i),
    storedIds(s.raw),
  )
  eq('status text after Undo', 'Activity restored.', s.statusText)
  eq('Undo button gone after Undo', false, s.undoPresent)
  eq('document.activeElement is the Clear activity button', true, s.activeIsClear)
  info('activeElement after Undo (tag/text)', `${s.activeTag} "${s.activeText}"`)

  await page.mouse.move(0, 0) // park the pointer so buttons render in rest style
  await page.screenshot({
    path: narrow ? `${DOCS}/TEAM-4162-narrow-undo.png` : `${DOCS}/TEAM-4162-undo.png`,
  })
}

async function s3(page, vp, narrow) {
  ctx = { viewport: vp, scenario: 'S3 Expiry' }
  await seed(page)
  const tClear = Date.now()
  await clearBtnOf(page).click()

  // t ~ 4900ms: Undo must still be there.
  await wait(Math.max(0, 4900 - (Date.now() - tClear)))
  let s = await snap(page)
  check(
    `Undo still present at t≈4900ms (actual t=${Date.now() - tClear}ms)`,
    true,
    s.undoPresent,
    s.undoPresent === true,
  )

  // t ~ 5200ms: gone.
  await wait(Math.max(0, 5200 - (Date.now() - tClear)))
  s = await snap(page)
  check(
    `Undo gone at t≈5200ms (actual t=${Date.now() - tClear}ms)`,
    false,
    s.undoPresent,
    s.undoPresent === false,
  )
  eq('status text after expiry', '', s.statusText)
  eq('empty-state paragraph present after expiry', true, s.emptyPresent)
  eq('empty-state paragraph exact copy', EXPECTED_EMPTY_COPY, s.emptyText)
  eq('Clear activity button absent after expiry', false, s.clearPresent)
  eq('ul count in section after expiry', 0, s.ulCount)
  eq('li count in section after expiry', 0, s.liCount)
  eq('[role=list] count in section after expiry', 0, s.roleListCount)
  eq('storage still empty after expiry', '[]', s.raw)

  if (!narrow) await page.screenshot({ path: `${DOCS}/TEAM-4162-expired.png` })
}

async function s4(page, vp) {
  ctx = { viewport: vp, scenario: 'S4 Reload (inside window)' }
  await seed(page)
  await clearBtnOf(page).click()
  await wait(400)
  await page.reload({ waitUntil: 'load' })
  await page.waitForSelector('section.activity-feed')
  let s = await snap(page)
  eq('empty-state paragraph present after reload inside window', true, s.emptyPresent)
  eq('empty-state copy after reload', EXPECTED_EMPTY_COPY, s.emptyText)
  eq('no Undo after reload inside window', false, s.undoPresent)
  eq('no Clear after reload inside window', false, s.clearPresent)
  eq('storage after reload inside window', '[]', s.raw)
  eq('li count after reload inside window', 0, s.liCount)

  ctx = { viewport: vp, scenario: 'S4 Reload (after Undo)' }
  await seed(page)
  const tClear = Date.now()
  await clearBtnOf(page).click()
  await undoBtnOf(page).click()
  const el = Date.now() - tClear
  check('Undo performed inside window', `< ${UNDO_WINDOW_MS} ms`, `${el} ms`, el < UNDO_WINDOW_MS)
  await page.reload({ waitUntil: 'load' })
  await page.waitForSelector('section.activity-feed')
  s = await snap(page)
  eq('li count after reload following Undo', 20, s.liCount)
  eq('stored entry count after reload following Undo', SEED_COUNT, storedLen(s.raw))
  eq('Clear activity present again after reload', true, s.clearPresent)
  eq('no Undo after reload (window state is not persisted)', false, s.undoPresent)
}

async function s5(page, vp) {
  ctx = { viewport: vp, scenario: 'S5 New entry + 2nd clear merge' }
  await seed(page)
  const tClear1 = Date.now()
  await clearBtnOf(page).click()

  // New entry arrives while the window is open.
  await toggleOf(page).click()
  let s = await snap(page)
  const newEntry = s.descriptions[0] || null
  check(
    'new li appears with text containing "Turned email notifications"',
    'contains "Turned email notifications"',
    newEntry,
    typeof newEntry === 'string' && newEntry.includes('Turned email notifications'),
  )
  info('exact new entry description', newEntry)
  eq('li count after entry added during window', 1, s.liCount)
  eq('Clear activity button reappeared', true, s.clearPresent)
  eq('Undo still present after new entry', true, s.undoPresent)
  eq('storage has exactly 1 entry after toggle', 1, storedLen(s.raw))
  eq('status text unchanged during window', 'Activity cleared.', s.statusText)

  // F2b: does the second Clear produce any DOM mutation on [role=status]?
  await page.evaluate(() => {
    const status = document.querySelector('section.activity-feed [role=status]')
    window.__qaStatusMutations = 0
    window.__qaStatusTextBefore = (status.textContent || '').trim()
    window.__qaObserver = new MutationObserver((records) => {
      window.__qaStatusMutations += records.length
    })
    window.__qaObserver.observe(status, {
      childList: true,
      characterData: true,
      subtree: true,
      attributes: true,
    })
  })

  const tClear2 = Date.now()
  const sinceFirst = tClear2 - tClear1
  check(
    'second Clear happens while first window still open',
    `< ${UNDO_WINDOW_MS} ms since first Clear`,
    `${sinceFirst} ms`,
    sinceFirst < UNDO_WINDOW_MS,
  )
  await clearBtnOf(page).click()
  await wait(150) // let any mutation flush
  const mut = await page.evaluate(() => ({
    count: window.__qaStatusMutations,
    before: window.__qaStatusTextBefore,
    after: (document.querySelector('section.activity-feed [role=status]').textContent || '').trim(),
  }))
  s = await snap(page)
  eq('status text after second Clear', 'Activity cleared.', s.statusText)
  info('F2b — [role=status] MutationObserver record count across 2nd Clear', mut.count)
  info('F2b — status text before / after 2nd Clear', `${mut.before} / ${mut.after}`)
  check(
    'F2b — status text actually CHANGED on 2nd Clear (would re-announce)',
    'changed (>0 mutations)',
    `${mut.count} mutations, text identical: ${mut.before === mut.after}`,
    mut.count > 0,
  )
  eq('Undo present after second Clear', true, s.undoPresent)
  eq('storage emptied by second Clear', '[]', s.raw)

  const el2 = Date.now() - tClear2
  check('Undo clicked inside 2nd window', `< ${UNDO_WINDOW_MS} ms`, `${el2} ms`, el2 < UNDO_WINDOW_MS)
  await undoBtnOf(page).click()
  s = await snap(page)
  eq('storage has 26 entries after merged Undo (25 seeded + 1 toggle)', 26, storedLen(s.raw))
  eq('li count after merged Undo', 20, s.liCount)
  check(
    'toggle entry is first (newest) after merged Undo',
    'contains "Turned email notifications"',
    s.descriptions[0],
    typeof s.descriptions[0] === 'string' && s.descriptions[0].includes('Turned email notifications'),
  )
  eq('status text after merged Undo', 'Activity restored.', s.statusText)
}

async function s6(page, vp) {
  ctx = { viewport: vp, scenario: 'S6 Keyboard only' }
  await seed(page)
  await page.mouse.click(5, 5)

  // Tab until the Clear button owns focus.
  const focusSeq = []
  let tabs = 0
  let onClear = false
  for (let i = 0; i < 10; i++) {
    await page.keyboard.press('Tab')
    tabs++
    const d = await page.evaluate(() => {
      const ae = document.activeElement
      const clearBtn = Array.from(
        document.querySelectorAll('section.activity-feed button'),
      ).find((b) => (b.textContent || '').trim() === 'Clear activity')
      return {
        label: ae
          ? `${ae.tagName}${ae.id ? '#' + ae.id : ''}${
              ae.getAttribute && ae.getAttribute('aria-label')
                ? '[' + ae.getAttribute('aria-label') + ']'
                : ae.textContent
                ? '"' + (ae.textContent || '').trim().slice(0, 24) + '"'
                : ''
            }`
          : 'null',
        isClear: !!clearBtn && ae === clearBtn,
      }
    })
    focusSeq.push(d.label)
    if (d.isClear) {
      onClear = true
      break
    }
  }
  check('Clear activity reachable by Tab within 10 presses', true, onClear, onClear)
  info('number of Tab presses to reach Clear activity', tabs)
  info('focus sequence while tabbing', focusSeq.join(' → '))

  // Enter activates Clear, focus lands on Undo.
  await page.keyboard.press('Enter')
  let s = await snap(page)
  eq('Enter on Clear: Undo present', true, s.undoPresent)
  eq('Enter on Clear: activeElement === Undo button', true, s.activeIsUndo)
  info('activeElement after Enter on Clear', `${s.activeTag} "${s.activeText}"`)

  // Space activates Undo, focus returns to Clear.
  await page.keyboard.press('Space')
  s = await snap(page)
  eq('Space on Undo: entries restored (li count)', 20, s.liCount)
  eq('Space on Undo: activeElement === Clear button', true, s.activeIsClear)

  // Now the mirrored pair: Space on Clear, Enter on Undo.
  await page.keyboard.press('Space')
  s = await snap(page)
  eq('Space on Clear: Undo present', true, s.undoPresent)
  eq('Space on Clear: activeElement === Undo button', true, s.activeIsUndo)
  await page.keyboard.press('Enter')
  s = await snap(page)
  eq('Enter on Undo: entries restored (li count)', 20, s.liCount)
  eq('Enter on Undo: activeElement === Clear button', true, s.activeIsClear)

  // Expiry with focus parked on Undo → focus must land on the heading.
  await page.keyboard.press('Space') // clear again via keyboard
  s = await snap(page)
  eq('pre-expiry: focus parked on Undo', true, s.activeIsUndo)
  await wait(5200)
  s = await snap(page)
  eq('after expiry: activeElement is #activity-feed-title', true, s.activeIsHeading)
  check(
    'after expiry: focus was NOT dropped to body',
    'not BODY',
    `${s.activeTag}${s.activeId ? '#' + s.activeId : ''}`,
    s.activeTag !== 'BODY',
  )
  info('activeElement tagName#id after expiry', `${s.activeTag}${s.activeId ? '#' + s.activeId : ''}`)
}

async function s7(page, vp) {
  ctx = { viewport: vp, scenario: 'S7 SR semantics' }
  await seed(page)
  let s = await snap(page)
  eq('exactly one [role=status] in section', 1, s.statusCount)
  eq('[role=status] tagName', 'P', s.statusTag)
  info('F2 — getComputedStyle(status).display BEFORE any clear (empty text)', s.statusDisplay)
  check(
    'F2 — empty status is NOT display:none (would stay in a11y tree)',
    "!== 'none'",
    s.statusDisplay,
    s.statusDisplay !== 'none',
  )

  await clearBtnOf(page).click()
  s = await snap(page)
  eq('status text after Clear', 'Activity cleared.', s.statusText)
  check('status display after Clear', "!== 'none'", s.statusDisplay, s.statusDisplay !== 'none')

  await undoBtnOf(page).click()
  s = await snap(page)
  eq('status text after Undo', 'Activity restored.', s.statusText)

  await clearBtnOf(page).click()
  await wait(5200)
  s = await snap(page)
  eq('status text after expiry', '', s.statusText)
  info('F2 — getComputedStyle(status).display AFTER expiry (empty text)', s.statusDisplay)
  eq('empty state has no ul', 0, s.ulCount)
  eq('empty state has no li', 0, s.liCount)
  eq('empty state has no [role=list]', 0, s.roleListCount)

  // Toggle 3x with 300ms spacing.
  ctx = { viewport: vp, scenario: 'S7 Toggle 3x' }
  await clearStorage(page)
  const pressed = []
  for (let i = 0; i < 3; i++) {
    await toggleOf(page).click()
    pressed.push(await toggleOf(page).getAttribute('aria-pressed'))
    if (i < 2) await wait(300)
  }
  s = await snap(page)
  eq('storage has exactly 3 entries after 3 toggles', 3, storedLen(s.raw))
  eq('3 li rendered after 3 toggles', 3, s.liCount)
  eq('aria-pressed cycles true/false/true', ['true', 'false', 'true'], pressed)
  const outer = await toggleOf(page).evaluate((el) => el.outerHTML)
  info('toggle outerHTML', outer)
  info('descriptions after 3 toggles (newest first)', s.descriptions)
}

async function s8(page, vp) {
  ctx = { viewport: vp, scenario: 'S8 Empty-snapshot Undo (F3)' }
  await seed(page)
  await page.evaluate(() => {
    const o = Storage.prototype.getItem
    Storage.prototype.getItem = function (k) {
      if (k === 'demo.activity') throw new Error('QA getItem')
      return o.call(this, k)
    }
  })

  await clearBtnOf(page).click()
  let s = await page.evaluate(() => {
    const section = document.querySelector('section.activity-feed')
    const status = section.querySelector('[role=status]')
    const btns = Array.from(section.querySelectorAll('button'))
    const has = (n) => btns.some((b) => (b.textContent || '').trim() === n)
    return {
      liCount: section.querySelectorAll('li').length,
      undoPresent: has('Undo'),
      clearPresent: has('Clear activity'),
      statusText: (status.textContent || '').trim(),
      activeTag: document.activeElement ? document.activeElement.tagName : null,
      activeText: document.activeElement ? (document.activeElement.textContent || '').trim().slice(0, 40) : null,
    }
  })
  info('after Clear with getItem throwing — li count', s.liCount)
  info('after Clear with getItem throwing — Undo present?', s.undoPresent)
  info('after Clear with getItem throwing — status text', s.statusText)
  eq('list empties in memory despite getItem throwing', 0, s.liCount)
  eq('Undo affordance still offered after failed read', true, s.undoPresent)

  await undoBtnOf(page).click()
  s = await page.evaluate(() => {
    const section = document.querySelector('section.activity-feed')
    const status = section.querySelector('[role=status]')
    const btns = Array.from(section.querySelectorAll('button'))
    const has = (n) => btns.some((b) => (b.textContent || '').trim() === n)
    return {
      liCount: section.querySelectorAll('li').length,
      undoPresent: has('Undo'),
      clearPresent: has('Clear activity'),
      statusText: (status.textContent || '').trim(),
      emptyPresent: !!section.querySelector('.activity-feed__empty'),
      activeTag: document.activeElement ? document.activeElement.tagName : null,
      activeId: document.activeElement ? document.activeElement.id || null : null,
      activeText: document.activeElement ? (document.activeElement.textContent || '').trim().slice(0, 40) : null,
    }
  })
  info('F3 — status text after Undo with EMPTY snapshot', s.statusText)
  check(
    'F3 — must NOT announce "Activity restored." when nothing was restored',
    'status text !== "Activity restored."',
    s.statusText,
    s.statusText !== 'Activity restored.',
  )
  eq('F3 — li count after empty-snapshot Undo', 0, s.liCount)
  info('F3 — Clear button present after empty-snapshot Undo?', s.clearPresent)
  info('F3 — empty-state paragraph present?', s.emptyPresent)
  info('F3 — activeElement after empty-snapshot Undo', `${s.activeTag}${s.activeId ? '#' + s.activeId : ''}`)
  check(
    'F3 — focus NOT dropped to body after empty-snapshot Undo',
    'not BODY',
    `${s.activeTag}${s.activeId ? '#' + s.activeId : ''}`,
    s.activeTag !== 'BODY',
  )
}

async function s9(page, vp, narrow) {
  ctx = { viewport: vp, scenario: 'S9 Visual' }
  await seed(page)
  let s = await snap(page)

  if (narrow) {
    check('scrollWidth <= 320 in default state', '<= 320', s.scrollWidth, s.scrollWidth <= 320)
  } else {
    info('scrollWidth in default state', s.scrollWidth)
  }

  // Clear button geometry at rest + rest colors.
  const clearGeom = await clearBtnOf(page).evaluate((el) => {
    const r = el.getBoundingClientRect()
    const cs = getComputedStyle(el)
    return { w: r.width, h: r.height, bg: cs.backgroundColor, color: cs.color }
  })
  check(
    'Clear button height ≈44px',
    '43–45 px',
    `${clearGeom.h.toFixed(2)} px`,
    clearGeom.h >= 43 && clearGeom.h <= 45,
  )
  check('Clear button width >= 24px', '>= 24 px', `${clearGeom.w.toFixed(2)} px`, clearGeom.w >= 24)
  eq('Clear button rest background', 'rgb(255, 255, 255)', clearGeom.bg)
  eq('Clear button rest color', 'rgb(71, 85, 105)', clearGeom.color)

  // Default-state screenshots FIRST, with the pointer parked away from the
  // button, so the evidence shows the rest style and not the hover style.
  await page.mouse.move(0, 0)
  await wait(120)
  if (narrow) await page.screenshot({ path: `${DOCS}/TEAM-4162-narrow.png` })
  else await page.screenshot({ path: `${DOCS}/TEAM-4162-default.png`, fullPage: true })

  // Hover colors.
  await clearBtnOf(page).hover()
  await wait(120)
  const hoverGeom = await clearBtnOf(page).evaluate((el) => {
    const cs = getComputedStyle(el)
    return { bg: cs.backgroundColor, color: cs.color }
  })
  eq('Clear button hover background', 'rgb(15, 23, 42)', hoverGeom.bg)
  eq('Clear button hover color', 'rgb(255, 255, 255)', hoverGeom.color)

  // Cleared state.
  await page.mouse.move(0, 0)
  await clearBtnOf(page).click()
  s = await snap(page)
  if (narrow) {
    check('scrollWidth <= 320 in cleared state', '<= 320', s.scrollWidth, s.scrollWidth <= 320)
  } else {
    info('scrollWidth in cleared state', s.scrollWidth)
  }
  const undoGeom = await undoBtnOf(page).evaluate((el) => {
    const r = el.getBoundingClientRect()
    const cs = getComputedStyle(el)
    return { w: r.width, h: r.height, bg: cs.backgroundColor, color: cs.color }
  })
  check(
    'Undo button height ≈44px',
    '43–45 px',
    `${undoGeom.h.toFixed(2)} px`,
    undoGeom.h >= 43 && undoGeom.h <= 45,
  )
  check('Undo button width >= 24px', '>= 24 px', `${undoGeom.w.toFixed(2)} px`, undoGeom.w >= 24)
  eq('Undo button rest background', 'rgb(255, 255, 255)', undoGeom.bg)
  eq('Undo button rest color', 'rgb(71, 85, 105)', undoGeom.color)
  await undoBtnOf(page).hover()
  await wait(120)
  const undoHover = await undoBtnOf(page).evaluate((el) => {
    const cs = getComputedStyle(el)
    return { bg: cs.backgroundColor, color: cs.color }
  })
  eq('Undo button hover background', 'rgb(15, 23, 42)', undoHover.bg)
  eq('Undo button hover color', 'rgb(255, 255, 255)', undoHover.color)

  // Restored state.
  await undoBtnOf(page).click()
  s = await snap(page)
  if (narrow) {
    check('scrollWidth <= 320 in restored state', '<= 320', s.scrollWidth, s.scrollWidth <= 320)
  } else {
    info('scrollWidth in restored state', s.scrollWidth)
  }
  await page.mouse.move(0, 0)
}

// ========================================================================= main

const browser = await chromium.launch()

for (const [w, h] of [
  [1280, 900],
  [320, 900],
]) {
  const vp = `${w}x${h}`
  const narrow = w === 320
  const context = await browser.newContext({ viewport: { width: w, height: h } })

  const scenarios = [
    ['S1+S2', s1s2],
    ['S3', s3],
    ['S4', s4],
    ['S5', s5],
    ['S6', s6],
    ['S7', s7],
    ['S8', s8],
    ['S9', s9],
  ]

  for (const [label, fn] of scenarios) {
    const page = await newPage(context)
    try {
      await fn(page, vp, narrow)
    } catch (err) {
      check(`${label} threw — scenario aborted`, 'no exception', String(err && err.message), false)
    } finally {
      await page.close()
    }
  }

  await context.close()
}

await browser.close()

// ------------------------------------------------------------------- reporting

const byVp = {}
for (const r of results) {
  byVp[r.viewport] ??= { PASS: 0, FAIL: 0, INFO: 0 }
  byVp[r.viewport][r.verdict]++
}

let tail = `\n## Console / pageerror capture (whole run)\n\n`
if (consoleMessages.length === 0) {
  tail += `No console messages and no page errors were emitted during the entire run.\n`
} else {
  tail += `| viewport | scenario | kind | message |\n| --- | --- | --- | --- |\n`
  for (const m of consoleMessages) {
    tail += `| ${m.viewport} | ${m.scenario} | ${m.kind} | ${cell(m.text)} |\n`
  }
}

tail += `\n## PASS/FAIL summary per viewport\n\n| viewport | PASS | FAIL | INFO | total assertions |\n| --- | --- | --- | --- | --- |\n`
for (const [vp, c] of Object.entries(byVp)) {
  tail += `| ${vp} | ${c.PASS} | ${c.FAIL} | ${c.INFO} | ${c.PASS + c.FAIL} |\n`
}

const fails = results.filter((r) => r.verdict === 'FAIL')
tail += `\n**Total: ${results.filter((r) => r.verdict === 'PASS').length} PASS, ${fails.length} FAIL, ${
  results.filter((r) => r.verdict === 'INFO').length
} INFO.**\n`

if (fails.length) {
  tail += `\n### Failing checks\n\n| viewport | scenario | check | expected | actual |\n| --- | --- | --- | --- | --- |\n`
  for (const f of fails) {
    tail += `| ${f.viewport} | ${f.scenario} | ${f.check} | ${cell(f.expected)} | ${cell(f.actual)} |\n`
  }
}

appendFileSync(LOG, tail)
console.log(tail)
console.log(`\nWrote ${LOG} (${results.length} rows).`)
